[package]
name = "helion-lexer-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
helion-lexer       = { path = "../helion-lexer" }
helion-parser      = { path = "../helion-parser" }
helion-ast         = { path = "../helion-ast" }
helion-interpreter = { path = "../helion-interpreter" }
thiserror          = "1.0"